defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: qrm_development

test:
  <<: *defaults
  database: qrm_test

  mongodb://heroku:smqogrm8c5ndhym9j1zqji@flame.mongohq.com:27105/app552417

# set these environment variables on your prod server
production:
  host: flame.mongohq.com 
  port: 27105
  username: heroku
  password: smqogrm8c5ndhym9j1zqji
  database: app552417 
